# -*- coding: utf-8 -*-
module K8sflow
  VERSION = '0.11.0'
  VERSION_NAMES = {1 => 'France II',
    2 => 'R.C. Rickmers',
    3 => 'Thomas W. Lawson',
    4 => 'Preussen',
    5 => 'Wyoming',
    6 => 'Wind Star',
    7 => 'Royal Clipper',
    8 => 'Potosí',
    9 => 'Maria Rickmers',
    10 => 'København',
    11 => 'France I',
    12 => 'Viking',
    13 => 'Amerigo Vespucci',
    14 => 'Sedov',
    15 => 'Great Republic',
    16 => 'Krusenstern',
    17 => 'Pamir',
    18 => 'Juan Sebastián de Elcano',
    19 => 'Esmeralda',
    20 => 'Star Clipper',
    21 => 'Star Flyer',
    22 => 'Dar Młodzieży',
    23 => 'Simon Bolivar',
    24 => 'Cuauhtémoc',
    25 => 'Gloria',
    26 => 'Créole',
    27 => 'Mir',
    28 => 'Statsraad Lehmkuhl',
    29 => 'Mircea',
    30 => 'Seute Deern',
    31 => 'Tovarishch',
    32 => 'Falls of Clyde',
    33 => 'Herzogin Cecilie',
    34 => 'Kaiwo Maru',
    35 => 'Kaiwo Maru II',
    36 => 'Lawhill',
    37 => 'Moshulu',
    38 => 'Nippon Maru',
    39 => 'Nippon Maru II',
    40 => 'Passat',
    41 => 'Palinuro',
    42 => 'Peking',
    43 => 'Pommern',
    44 => 'Sea Cloud',
    45 => 'Wind Surf',
    46 => 'Eagle',
    47 => 'Sagres II',
    48 => 'Phocéa',
    49 => 'Archibald Russell',
    50 => 'Wind Spirit'}

end
